# feature_embedding/integrator.py
# This module acts as an integrator, combining multiple types of drug features
# generated by other modules into a single, unified dictionary.

import torch
from rdkit import Chem

# Import the individual feature generators from sibling modules within this package.
from feature_embedding.morgan import generate_morgan_fingerprint
from feature_embedding.gin import generate_gin_embedding
from feature_embedding.dti import DtiPredictor

def generate_drug_features(smiles: str, dti_predictor: DtiPredictor) -> dict:
    """
    Generates all required drug features by calling individual generator modules.
    
    Args:
        smiles (str): The input SMILES string for the drug.
        dti_predictor (DtiPredictor): An initialized DtiPredictor instance.

    Returns:
        dict: A dictionary containing the 'morgan', 'gin', and 'dti' feature vectors.
    """
    # Convert the SMILES string to an RDKit molecule object for processing.
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"Invalid SMILES string: {smiles}")

    # Generate each feature vector using its dedicated, imported function.
    morgan_vec = generate_morgan_fingerprint(mol)
    gin_vec = generate_gin_embedding(mol)
    dti_vec = dti_predictor.predict_for_smiles(smiles)

    # Return the combined features in a dictionary, ready for the model.
    return {'morgan': morgan_vec, 'gin': gin_vec, 'dti': dti_vec}